#pragma kernel Flow
#pragma kernel Flow2

struct Vert
{
    float3 pos;
    float3 vel;
    float3 nor;
    float3 tangent;
    float3 axis;
    float  life;
};

float4x4 _Transform;

RWStructuredBuffer<Vert> _VertBuffer;

int _VertBuffer_COUNT;

#include "../../Chunks/safeID.cginc"
#include "../../Chunks/snoise.cginc"
#include "../../Chunks/hash.cginc"
#include "../../Chunks/curlNoise.cginc"
#include "../../Chunks/ParticleAxisHelpers.cginc"


Texture2D<float4> _HeightMap;
SamplerState      sampler_HeightMap;

Texture2D<float4> _WindMap;
SamplerState      sampler_WindMap;
float3            _MapSize;
float3            _MapOffset;


float2 getUV( float3 pos )
{
    return ( pos.xz + _MapOffset.xz ) / _MapSize.xz;
}

float3 terrainPos( float3 pos )
{

    float2 uv = getUV( pos );
    return float3( pos.x , _HeightMap.SampleLevel( sampler_HeightMap , uv , 1 ).x * _MapSize.y * 2 , pos.z );
}


float terrainHeight( float3 pos )
{

    float2 uv = getUV( pos );
    float  h  = _HeightMap.SampleLevel( sampler_HeightMap , uv , 1 ).x * _MapSize.y * 2;
    return pos.y - h;
}


float3 getWindPower( float3 pos )
{
    float2 uv = getUV( pos );


    if ( uv.x < 0 || uv.x > 1 || uv.y < 0 || uv.y > 1 )
    {
        return 0;
    }

    float4 windVal = _WindMap.SampleLevel( sampler_WindMap , uv , 1 );

    return windVal.xyz;
}

float _Time;

void DoInit( inout Vert vert , float pID )
{
    vert.life = ( hash( float( pID ) ) + hash( float( pID * 30 ) ) + hash( float( pID * 23 ) ) ) / 3;
    vert.axis = newAxis( float( pID ) );
}

float3 _WrenVel;

float3 hash33( float p )
{
    float3 p3 = frac( p * float3( 0.1031 , 0.11369 , 0.13787 ) );
    p3 += dot( p3 , p3.yzx + 19.19 );
    return frac( ( p3.xxy + p3.yzz ) * p3.zyx );
}

float3 DoRemitPosition( int id )
{
    float  v       = float( id );
    float3 emitPos = float3(
        hash( v * 20 + hash( v * 212.44 + _Time ) * 10 + _Time ) ,
        hash( v * 30 + hash( v * 313.55 + _Time ) * 20 + _Time * 2 ) ,
        hash( v * 40 + hash( v * 414.66 + _Time ) * 30 + _Time * 3 )
    );

    emitPos = ( hash33( v * 3 + _Time * 2 ) + hash33( v + _Time ) ) / 2;
    emitPos -= 0.5;


    emitPos *= 400;

    float3 p = mul( _Transform , float4( emitPos , 1 ) ).xyz;;

    p += _WrenVel * 100;

    float d = terrainHeight( p );

    if ( d < 0 )
    {
        return terrainPos( p ) + float3( 0 , 4 , 0 );
    }

    return p;
}

float3 DoRemitVelocity( int p )
{
    return 0;

}


float3 DoForce( inout Vert vert , int pID )
{

    if ( length( vert.vel ) == 0 )
    {
        vert.vel = getWindPower( vert.pos ) * .1;
    }


    float3 force = 0;
    //  force += 1.4*curlNoise(vert.pos * .4);
    // force +=  mul( _Transform, float4( 0,1 ,0,0)).xyz;
    force += getWindPower( vert.pos ) * 10;

    float d = terrainHeight( vert.pos );
    if ( d < .1 )
    {
        force += float3( 0 , 1 , 0 ) * ( .1 - d ) * .1;
    }

    force *= .001 * ( 1 + hash( pID * 1021. ) + hash( pID * 133. ) ) / 3;


    vert.nor = mul( rotation( vert.axis , vert.life * 10 * ( hash( float( pID * 123 ) ) + 1 ) ) , float4( 0 , 0 , 1 , 0 ) ).xyz;
    // Giving the vert a tangent
    vert.tangent = normalize( cross( vert.axis , normalize( vert.nor ) ) );

    return force;
}

float DoLife( Vert v , int pID )
{
    return .001 * ( 3 + sin( float( pID ) * 4441.4 + sin( float( pID ) * 11.3 ) * 103.14 ) * 3013.4 );
}

float DoDampening( Vert v , int pID )
{
    return .8;
}

#define NR_THREADS 128

[numthreads(NR_THREADS,1,1)]
void Flow( uint3 id : SV_DispatchThreadID )
{
    #include "../../Chunks/SimplifiedSimulation.cginc"
}

float3 _CameraForward;

float3 randomPosition( int pID )
{
    return float3( hash( float( pID ) * 20 ) + hash( float( pID ) * 23.1 ) - 1 , hash( float( pID ) * 11 ) + hash( float( pID ) * 33.1 ) - 1 , hash( float( pID ) * 231 ) + hash( float( pID ) * 331 ) ) * .5;
}

#define NR_THREADS 128

[numthreads(NR_THREADS,1,1)]
void Flow2( uint3 id : SV_DispatchThreadID )
{

    int pID   = id.x;
    pID       = safeID( pID , _VertBuffer_COUNT );
    Vert vert = _VertBuffer[ pID ];


    if ( vert.pos.x == 0 && vert.pos.y == 0 && vert.pos.z == 0 )
    {
        DoInit( vert , float( pID ) );

        vert.pos = DoRemitPosition( pID ); // ) mul( _Transform , float4( 1000 * randomPosition( pID ) , 1 ) );
        vert.vel = DoRemitVelocity( pID );
    }


    if ( vert.life < 0 )
    {

        vert.pos = DoRemitPosition( pID ); // mul( _Transform , float4( 1000 * randomPosition( pID ) , 1 ) );

        vert.vel  = DoRemitVelocity( pID );
        vert.life = 1; //

    }
    else
    {

        float3 force = 0; // DoForce( vert , pID); //float3(0,0,0);
        force += getWindPower( vert.pos ) * 1;



        vert.vel = getWindPower( vert.pos ) * .3;

        float d = terrainHeight( vert.pos );
        if ( d < 1 )
        {
            vert.vel = vert.vel * float3( 1 , 0 , 1 ) * 1;
            vert.vel += float3( 0 , 1 , 0 ) * ( 1 - d ) * .1;
        }

        //   vert.vel += force * 10.1; /// * .00004 * (1+hash(pID*1021.))/2;

        vert.life -= .001 * ( 3 + sin( float( pID ) ) );
        vert.pos += vert.vel;

        vert.vel *= .9; //DoDampening( vert , pID );

        vert.nor     = cross( normalize( vert.vel ) , _CameraForward );
        vert.tangent = normalize( vert.vel );

    }



    _VertBuffer[ pID ] = vert;


}
