using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class SpeedTrapLeaderboardEntryModel
{
    [RealtimeProperty(1, true)]
    private float _speedTrapTime;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class SpeedTrapLeaderboardEntryModel : RealtimeModel {
    public float speedTrapTime {
        get {
            return _speedTrapTimeProperty.value;
        }
        set {
            if (_speedTrapTimeProperty.value == value) return;
            _speedTrapTimeProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public enum PropertyID : uint {
        SpeedTrapTime = 1,
    }
    
    #region Properties
    
    private ReliableProperty<float> _speedTrapTimeProperty;
    
    #endregion
    
    public SpeedTrapLeaderboardEntryModel() : base(null) {
        _speedTrapTimeProperty = new ReliableProperty<float>(1, _speedTrapTime);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _speedTrapTimeProperty.UnsubscribeCallback();
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _speedTrapTimeProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _speedTrapTimeProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.SpeedTrapTime: {
                    changed = _speedTrapTimeProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _speedTrapTime = speedTrapTime;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
