using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class SpeedTrapLeaderboardModel
{
    [RealtimeProperty(1, true, true)]
    private RealtimeDictionary<SpeedTrapLeaderboardEntryModel> _speedTrapEntries;
}



/* ----- Begin Normal Autogenerated Code ----- */
public partial class SpeedTrapLeaderboardModel : RealtimeModel {
    public Normal.Realtime.Serialization.RealtimeDictionary<SpeedTrapLeaderboardEntryModel> speedTrapEntries {
        get => _speedTrapEntries;
    }
    
    public enum PropertyID : uint {
        SpeedTrapEntries = 1,
    }
    
    #region Properties
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<SpeedTrapLeaderboardEntryModel>> _speedTrapEntriesProperty;
    
    #endregion
    
    public SpeedTrapLeaderboardModel() : base(null) {
        RealtimeModel[] childModels = new RealtimeModel[1];
        
        _speedTrapEntries = new Normal.Realtime.Serialization.RealtimeDictionary<SpeedTrapLeaderboardEntryModel>();
        childModels[0] = _speedTrapEntries;
        
        SetChildren(childModels);
        
        _speedTrapEntriesProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<SpeedTrapLeaderboardEntryModel>>(1, _speedTrapEntries);
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _speedTrapEntriesProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _speedTrapEntriesProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.SpeedTrapEntries: {
                    changed = _speedTrapEntriesProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _speedTrapEntries = speedTrapEntries;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
