#pragma kernel NewTruth

#include "../Chunks/safeID.cginc"
#include "../Chunks/snoise.cginc"
#include "../Chunks/curlNoise.cginc"
#include "../Chunks/hash.cginc"


struct Vert
{
    float3 pos;
    float3 vel;
    float3 nor;
    float3 tan;
    float2 uv;
    float  isBeingAdded;
    float  type;
};


RWStructuredBuffer<Vert> _VertBuffer;
int                      _VertBuffer_COUNT;


StructuredBuffer<int> _NumCrystalsBuffer;


int   _Count;
float _DT;

float _StreamWidth;
float _StreamHeight;

//#include "../Chunks/nanCheckFeather.cginc"
#define NR_THREADS 128

float4x4 _Transform;
float4x4 _TruthAdder;

int _ToAdd;
int _ToAddID;


float _Time;


float3 VecToRay( float3 ro , float3 rd , float3 pos )
{

    float3 p2      = ro - rd * 200;
    float3 pa      = pos - ro;
    float3 ba      = ro - p2;
    float  h       = dot( pa , ba ) / dot( ba , ba );
    float3 pOnLine = h * rd * 200 + ro;

    float3 inLine = pos - pOnLine;

    return inLine; //normalize(inLine) * force *  (1 - clamp( length(inLine) / radius , 0 , 1));
}


float3 CurlAroundBirdForce( float3 pos , float3 wrenPos , float3 wrenVel )
{
    float3 wvel = wrenVel;
    if ( length( wvel ) < .01 )
    {
        wvel = float3( 0 , 0 , .001 );
    }

    float3 outVec = VecToRay( wrenPos , normalize( wvel ) , pos );

    float3 f = -normalize( outVec ) * 30.3;
    f += 1.05 * length( wvel ) * normalize( cross( wvel , outVec ) ) / length( outVec ); //saturate((1-vert.debug)* 10) *1000 * normalize(delta) / length(delta);

    return ( wvel * 10 / pow( length( wrenPos - pos ) , 2 ) ) + f * pow( length( wvel ) * .05 , 2 ) / ( .4 + length( wrenPos - pos ) );


}


float3 _WrenPos;
float3 _WrenVel;

int _Total;


[numthreads(NR_THREADS,1,1)]
void NewTruth( uint threadID : SV_GroupIndex , uint3 u3GroupID : SV_GroupID , uint3 id : SV_DispatchThreadID )
{


    uint pID = threadID + u3GroupID.x * NR_THREADS;

    pID = safeID( pID , _VertBuffer_COUNT );

    Vert vert = _VertBuffer[ pID ];


    int  type    = 6;
    int  isExtra = -1;
    int  currCrystals;
    bool isBeingAdded = false;
    for ( int i = 0; i < 7; i++ )
    {

        if ( pID >= currCrystals && pID < currCrystals + _NumCrystalsBuffer[ i ] )
        {
            vert.type = float( i );

            if ( _ToAddID == i )
            {

                if ( pID > currCrystals + _NumCrystalsBuffer[ i ] - _ToAdd )
                {
                    isBeingAdded = true;
                }

            }

            break;
        }

        currCrystals += _NumCrystalsBuffer[ i ];

    }

    if ( isBeingAdded )
    {
        vert.isBeingAdded = 1;
    }
    else
    {
        vert.isBeingAdded = 0;
    }




    int row    = vert.type;
    int column = pID - currCrystals;

    float3 startPos = float3( float( column ) * .01 , float( row ) * .1 , isBeingAdded * .1 );
    startPos *= 1;


    float3 targetPos = mul( _Transform , float3( 0 , 0 , 0 ) ).xyz;

    float3 rand = float3( hash( float2( pID , 0 ) ) , hash( float2( pID * 10 , 1 ) ) , hash( float2( pID * 20 , 2 ) ) );
    rand -= .5;


    // rand *= 100;
    // pull towards the being added target
    if ( isBeingAdded )
    {
        targetPos = mul( _TruthAdder , float4( rand , 1 ) ).xyz;

    }
    else
    {
        targetPos = mul( _Transform , float4( rand , 1 ) ).xyz;
    }

    rand += normalize( ( float3( hash( float2( vert.type , 0 ) ) , hash( float2( vert.type * 10 , 1 ) ) , hash( float2( vert.type * 20 , 2 ) ) ) - .5 ) ) * 3;

    float3 trueCenter = mul( _Transform , float4( 0 , 0 , 0 , 1 ) ).xyz;

    float3 outVec = vert.pos - trueCenter;
    outVec.y      = 0;

    float3 curlVec = cross( outVec , float3( 0 , 1 , 0 ) );


    if ( vert.pos.x == 0 || vert.pos.y == 0 || vert.pos.z == 0 )
    {
        vert.pos = targetPos;
        vert.vel = rand * 400;;
    }

    float3 force    = 0;
    float3 toTarget = targetPos - vert.pos;


    float totalNormalized = float( _Total ) / 100000;

    if ( length( toTarget ) < 0.00001 )
    {
        vert.pos = targetPos;
        //vert.vel = 0;
    }
    else
    {


        force += toTarget * 5;

        force += ( length( toTarget ), 4 ) * toTarget * 10 / ( 1 + 10 * totalNormalized );
        if ( isBeingAdded )
        {
            force += toTarget * 3000;
        }
        else
        {
            force += curlVec * 100;
            force -= outVec * 10;
        }

        force -= normalize( toTarget ) * 100 * ( 3 + 3 * sin( _Time ) ) * ( 2 * totalNormalized );

    }

    if ( isBeingAdded )
    {
        force += curlNoise( vert.pos + float3( 0 , _Time * .1 , 0 ) ) * 1000;
    }
    else
    {

        force += curlNoise( vert.pos * ( .1 + pow( ( sin( _Time * .5 ) + 1 ) / 2 , 3 ) * .4 ) + float3( vert.type , _Time * .1 , 0 )
            )
            * 500;
    }

    if ( isBeingAdded )
    {
        if ( length( toTarget ) > 100 )
        {

            vert.pos = targetPos;
            vert.vel = rand * 40;
            force    = 0;

        }
    }




    float3 wv = _WrenVel;
    if ( length( wv ) < .01 )
    {
        wv = float3( 0 , 0 , .001 );
    }

    force += CurlAroundBirdForce( vert.pos , _WrenPos , wv ) * 100 * ( rand * .2 + 1 ) * 1;


    float dt = .002;


    if ( !isBeingAdded )
    {
        // force += centerSimForce * 100;
        // force += vortex * 10000.1;
    }


    // force = 0;

    if ( length( force ) > 100000 )
    {
        force = normalize( force ) * 100000;
    }

    if ( length( vert.vel ) > 100000 )
    {
        vert.vel = normalize( vert.vel ) * 100000;
    }

    force *= 1;

    vert.vel += force * dt;
    vert.pos += vert.vel * dt;
    vert.vel *= .9;






    _VertBuffer[ pID ] = vert;

}
