using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class RaceLeaderboardEntryModel
{
    [RealtimeProperty(1, true)]
    private float _raceTime;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RaceLeaderboardEntryModel : RealtimeModel {
    public float raceTime {
        get {
            return _raceTimeProperty.value;
        }
        set {
            if (_raceTimeProperty.value == value) return;
            _raceTimeProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public enum PropertyID : uint {
        RaceTime = 1,
    }
    
    #region Properties
    
    private ReliableProperty<float> _raceTimeProperty;
    
    #endregion
    
    public RaceLeaderboardEntryModel() : base(null) {
        _raceTimeProperty = new ReliableProperty<float>(1, _raceTime);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _raceTimeProperty.UnsubscribeCallback();
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _raceTimeProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _raceTimeProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.RaceTime: {
                    changed = _raceTimeProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _raceTime = raceTime;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
