using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class RaceLeaderboardModel
{
    [RealtimeProperty(1, true, true)]
    private RealtimeDictionary<RaceLeaderboardEntryModel> _raceEntries;
}



/* ----- Begin Normal Autogenerated Code ----- */
public partial class RaceLeaderboardModel : RealtimeModel {
    public Normal.Realtime.Serialization.RealtimeDictionary<RaceLeaderboardEntryModel> raceEntries {
        get => _raceEntries;
    }
    
    public enum PropertyID : uint {
        RaceEntries = 1,
    }
    
    #region Properties
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<RaceLeaderboardEntryModel>> _raceEntriesProperty;
    
    #endregion
    
    public RaceLeaderboardModel() : base(null) {
        RealtimeModel[] childModels = new RealtimeModel[1];
        
        _raceEntries = new Normal.Realtime.Serialization.RealtimeDictionary<RaceLeaderboardEntryModel>();
        childModels[0] = _raceEntries;
        
        SetChildren(childModels);
        
        _raceEntriesProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<RaceLeaderboardEntryModel>>(1, _raceEntries);
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _raceEntriesProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _raceEntriesProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.RaceEntries: {
                    changed = _raceEntriesProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _raceEntries = raceEntries;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
