using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class PersistentWrenStorageModel
{
    [RealtimeProperty(1, true, true)]
    private RealtimeDictionary<PersistentWrenModel> _wrens;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class PersistentWrenStorageModel : RealtimeModel {
    public Normal.Realtime.Serialization.RealtimeDictionary<PersistentWrenModel> wrens {
        get => _wrens;
    }
    
    public enum PropertyID : uint {
        Wrens = 1,
    }
    
    #region Properties
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<PersistentWrenModel>> _wrensProperty;
    
    #endregion
    
    public PersistentWrenStorageModel() : base(null) {
        RealtimeModel[] childModels = new RealtimeModel[1];
        
        _wrens = new Normal.Realtime.Serialization.RealtimeDictionary<PersistentWrenModel>();
        childModels[0] = _wrens;
        
        SetChildren(childModels);
        
        _wrensProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<PersistentWrenModel>>(1, _wrens);
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _wrensProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _wrensProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Wrens: {
                    changed = _wrensProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _wrens = wrens;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
